Fixed calling undefined method setOutput
Summary: This is related to the story User images are no longer loading

Test Plan:
When uploading new image file in it throws error in network tab.
Fatal error: Uncaught Error: Call to undefined method Netric\Controller\FilesController::setOutput() in /var/www/html/src/Netric/Controller/FilesController.php on line 169

Reviewers: sky, marl.tumulak

Subscribers: jan, joemariel

Differential Revision: https://src.aereus.com/D651